Removed poll app and added basic homepage for website.
nbovee/shop-inventory pull request #13
Opened 2024-04-11 17:53 UTC by sunjimmy1

Removed the Polls App and added a basic homepage.

2024-04-16 02:53 UTC, nbovee approved these changes
Looks good to reset us to a base starting point

2024-04-16 03:38 UTC, nbovee commented on website/website/settings.py
0.0.0.0 refers to outside hosts, best not to have that in here.

2024-04-16 03:41 UTC, nbovee requested changes
0.0.0.0 should be removed from allowable hosts

Please add a tests.py file back to repo to allow it to have a baseline test, ex containing:
```
def test_exists():
    assert True
```

2024-04-18 18:20 UTC, sunjimmy1 commented
Closes #2

2024-04-25 05:13 UTC, nbovee approved these changes
👍

2024-04-25 05:14 UTC, merged